### ISSUE TITLE
Weird spacing

### ISSUE THREAD

**Issue by soranoo** [soranoo/next-css-obfuscator#10]
hmm what was that weird spacing

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/a2a4668e-32c7-49c5-bf9f-bfe2eb813ef0)

_Originally posted by @hoangnhan2ka3 in https://github.com/soranoo/next-css-obfuscator/issues/9#issuecomment-1925548768_

**Comment by hoangnhan2ka3** [comment]
I discovered that when I break a line like this, it will cause the above spacing error:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/dfb5aa6f-5dc9-4c29-938c-beff5c84908c)

When I put `className` on the same line as usual, everything is fine:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/e7898466-f033-4ce7-b38f-dd50e50fa987)

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/f25a989c-63b2-4ac1-8f14-b9eb98686983)

**Comment by hoangnhan2ka3** [comment]
Oh here we go again https://github.com/soranoo/next-css-obfuscator/issues/4 🫡

**Comment by hoangnhan2ka3** [comment]
I don't know, but...

I just tried using `cssnano` in `postcss.config.js` and the problem seems to be resolved

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/8d380777-bbf4-4a78-98b2-e7ec2090cb12)

Multi-line `className`:

<img width="782" alt="image" src="https://github.com/soranoo/next-css-obfuscator/assets/147973044/86f942ec-5c60-4e9f-a38d-26741b873a14">

Result ✅:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/4e3ebc3e-3319-4857-8723-3124f54bd4c0)

Although in production `cssnano` reports some `Parse error` or `UNKNOWN_DIMENSION` errors if you use `viewport unit` in a `calc` with other units (?)

_eg: `calc(100% - 0.94dvw)`..._

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/07f2be13-0a06-43db-8c8b-21e282759293)

But in general, these errors are harmless, so this can be considered an effective temporary method.

**Comment by hoangnhan2ka3** [comment]
Or do you have any updates on this issue in `v2.1.4` @soranoo ? I hope I don't misunderstand

**Comment by soranoo** [comment]
`2.1.4` is just the official release of `2.1.4-beta.1`. Nothing related to this issue.

**Comment by hoangnhan2ka3** [comment]
Sorry, I have a problem unrelated to this issue, which is `caching`.

You know, every time you `run build` the obfuscate process will start from the beginning, meaning the `random obfuscated classes` will be completely different from the previous time. This causes nextjs `cache` related issue.

If a user has visited my page before, then after I update (new deployed), and they reload the page without clearing the cache, it will look like this:

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/2912d931-e5ec-48b7-b960-13eaf4f66ebe)

And no matter how many times they try to 'refresh' the website, it will still look the same.

Unless they press `Ctrl + Shift + R` (aka `hard reload`), the site is updated.

![image](https://github.com/soranoo/next-css-obfuscator/assets/147973044/e834c516-95f1-4af0-a4e3-8310b38d9493)

Even when I try `view page source` without `hard reload`, the css file doesn't have any new obfuscated class, which causes an error like my website doesn't have `css` at all.

Do you have the same problem in your version of `Next Js`, or do you have any advice for me, I've been searching for it all night.

**Comment by hoangnhan2ka3** [comment]
The problem probably only occurs when I enable `next-css-obfuscator`.

If you don't enable it from the beginning, the TW classes will just update the new values ​​after each deployment, and the old classes don't need to be changed, and it will be cached, I think.

**Comment by soranoo** [comment]
Please open a new issue for **ANY ISSUE NOT** related to the current one.

**Comment by hoangnhan2ka3** [comment]
Yes, I just wanted to ask your opinion if this is considered an issue with this plugin 🫡.

**Comment by soranoo** [comment]
Since the issue was not caused by this package, I decided to leave it alone.
